// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --transpile-only prisma/seed.ts",
  },
  datasource: {
    url: (() => {
      const raw = process.env["DATABASE_URL"] ?? "";
      if (!raw || /localhost|127\.0\.0\.1/.test(raw)) return raw;
      const [base, query] = raw.split("?");
      const params = (query ?? "")
        .split("&")
        .filter((part) => part && !/^sslmode=/i.test(part) && !/^ssl=/i.test(part));
      params.push("sslmode=no-verify");
      return `${base}?${params.join("&")}`;
    })(),
  },
});
