// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --transpile-only prisma/seed.ts",
  },
  datasource: {
    url: (() => {
      const url = process.env["DATABASE_URL"] ?? "";
      if (!url || /localhost|127\.0\.0\.1/.test(url) || /sslmode=/i.test(url)) return url;
      return url.includes("?") ? `${url}&sslmode=require` : `${url}?sslmode=require`;
    })(),
  },
});
